
#################################################################
## Home Assistant

homeassistant:
  name: Home Assistant
  latitude: !secret halatitude
  longitude: !secret halongitude
  elevation: 250
  unit_system: imperial
  time_zone: America/Detroit
  packages: !include_dir_named packages/

frontend:
  javascript_version: latest
  themes:
    dark:
      primary-color: '#36454f'

config:

http:
  server_port: !secret server_port
  api_password: !secret api_password
  base_url: !secret base_url
  use_x_forwarded_for: true
  trusted_proxies: !secret trusted_proxies
  ip_ban_enabled: true
  login_attempts_threshold: 5

group:
  default_view:
    view: yes

lovelace:
  mode: yaml

discovery:
  ignore:
    - plex_mediaserver
    - igd

recorder:
  purge_interval: 1
  purge_keep_days: 3
  include:
    domains:
      - alarm_control_panel
      - binary_sensor
      - climate
      - input_boolean
      - input_select
      - input_datetime
      - light
      - media_player
      - switch
      - vacuum
      - lock
    entities:
      - sensor.dishwasher_status
      - sensor.meter_outlet_current
      - sensor.meter_outlet_power
      - sensor.kwikset_touchpad_electronic_deadbolt_alarm_level_2
      - sensor.kwikset_touchpad_electronic_deadbolt_alarm_type_2
      - sensor.dining_room_thermostat_temperature
      - sensor.dining_room_thermostat_humidity
      - sensor.roomba_status
      - sensor.home_assistant_release
      - sensor.current_version
  exclude:
    entities:
      - binary_sensor.backdoor_contact_sensor
      - binary_sensor.frontdoor_contact_sensor
      - binary_sensor.sidedoor_contact_sensor
      - binary_sensor.mckinley_away
      - binary_sensor.dining_room_thermostat_is_using_emergency_heat
      - binary_sensor.dining_room_thermostat_online
      - binary_sensor.dining_room_thermostat_is_locked
      - binary_sensor.dining_room_thermostat_has_leaf
      - binary_sensor.dining_room_thermostat_fan
      - light.hue_lamp_1
      - light.hue_lamp_2
      - light.hue_lamp_3
      - light.hue_color_lamp_1
      - light.hue_color_lamp_2
      - light.hue_color_lamp_3
      - light.hue_color_light_1
      - light.hue_color_light_1_2
      - light.hpmusicgroup
      - light.group_for_wakeup
      - light.living_room
      - light.master
      - input_boolean.alarmclock_cancel
      - media_player.muffin_stuffin
      - input_select.playlist_content
      - input_select.playlist_source
      - switch.livingroom_outlet_switch_3
      - switch.livingroom_outlet_switch_2
      - switch.livingroom_outlet_switch

history:

logbook:

logger:
  default: info
  logs:
    homeassistant.components.roomba: error
    homeassistant.components.device_tracker.netgear: fatal
    pynetgear: warn
    pychromecast.socket_client: fatal
    pychromecast: fatal
    socket_client: fatal
    homeassistant.components.light.hue: fatal
    roomba.roomba.Roomba: warn

sun:

sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'time_date'
      - 'time_utc'
      - 'beat'

python_script:

#################################################################
## Media Players

media_player:
  - platform: vizio
    name: viziotv
    host: !secret viziohost
    access_token: !secret vizioaccess_token
    suppress_warning: true
  - platform: nadtcp2
    name: nadc338
    max_volume: -20
    min_volume: -70
    host: !secret nadtcp2host


#################################################################
## Lights

zwave:
  polling_interval: 30000
  device_config:
    light.livingroom_light_level:
      polling_intensity: 1
      refresh_value: true
    light.kitchen_light_level:
      polling_intensity: 1
      refresh_value: true
    light.diningroom_light_level:
      polling_intensity: 1
      refresh_value: true
    light.bedroom_light_level:
      polling_intensity: 1
      refresh_value: true
    light.bathroom_light_level:
      polling_intensity: 1
      refresh_value: true
    light.hallway_light_level:
      polling_intensity: 1
      refresh_value: true

light:
  - platform: hue
    allow_unreachable: true
    allow_hue_groups: true


#################################################################
## Things

vacuum:
  - platform: roomba
    host: !secret roombahost
    username: !secret roombausername
    password: !secret roombapassword

weather:
  - platform: darksky
    api_key: !secret darksky

nest:
  client_id: !secret nestclient_id
  client_secret: !secret nestclient_secret

#################################################################
## Security / Occupancy

alarm_control_panel:
  platform: manual
  name: Main
  pending_time: 15
  trigger_time: 99999999

zoneminder:
  host: !secret zmhost
  ssl: true
  username: homeassistant
  password: !secret zmpassword

camera:
  - platform: zoneminder
  - platform: generic
    still_image_url: https://icons.wxug.com/data/weather-maps/radar/united-states/cadillac-michigan-region-current-radar-animation.gif
    name: Midwest Radar

device_tracker:
  - platform: netgear
    host: !secret netgearhost
    username: !secret netgearusername
    password: !secret netgearpassword
    port: 80
    interval_seconds: 12
    new_device_defaults:
      track_new_devices: False

zone:
  name: Home
  latitude: !secret zonelatitude
  longitude: !secret zonelongitude
  radius: 200


#################################################################
## Notifications and Google Assistant

twilio:
  account_sid: !secret twilioaccountsid
  auth_token: !secret twilioauthtoken

notify:
  - name: twilio_calling
    platform: twilio_call
    from_number: !secret twiliofromnumber
  - name: html5
    platform: html5
    gcm_api_key: !secret gcpapikey
    gcm_sender_id: !secret gcpsenderid
  - name: ga_broadcast
    platform: rest
    resource: !secret ga_broadcast
  - name: ga_command
    platform: rest
    resource: !secret ga_command

google_assistant:
  expose_by_default: false
  project_id: !secret ga_project_id
  api_key: !secret ga_api_key
  entity_config:
    light.livingroom_light_level:
      expose: true
      name: Living Room Lights
    light.kitchen_light_level:
      expose: true
      name: Kitchen Lights
    light.diningroom_light_level:
      expose: true
      name: Dining Room Lights
    light.bedroom_light_level:
      expose: true
      name: Bedroom Lights
    light.bathroom_light_level:
      expose: true
      name: Bathroom Lights
    light.hallway_light_level:
      expose: true
      name: Hallway Lights
    light.nightstand:
      expose: true
      name: Nightstand Lights
    light.nightstand1:
      expose: true
      name: !secret user2ns
    light.nightstand2:
      expose: true
      name: !secret user1ns
    switch.bedroom_outlet_switch_3:
      expose: true
      name: Bedroom Fan Switch
      aliases:
        - Bedroom Fan
        - Fan
    switch.kitchen_outlet_switch:
      expose: true
      name: Espresso Machine Switch
      aliases:
        - Espresso Machine
        - Coffee Machine
        - Kitchen Outlet
    media_player.nadc338:
      expose: true
      name: Stereo Switch
      aliases:
        - Stereo
        - Nad
    media_player.viziotv:
      expose: true
      name: TV Switch
      aliases:
        - TV
        - Vizio
    scene.dinner:
      expose: true
      name: Dinner Scene
    scene.watching_tv:
      expose: true
      name: Watching TV Scene
    scene.goodmorning:
      expose: true
      name: GoodMorning Scene
    scene.bedtime:
      expose: true
      name: Bedtime Scene
    scene.mia_bedtime:
      expose: true
      name: Mia Bedtime
    scene.all_things_off:
      expose: true
      name: All Things Off Scene
    script.cancel_alarm:
      expose: true
      name: Cancel Alarm
    script.playlist_stop:
      expose: true
      name: Playlist Stop
