
#################################################################
## Home Assistant

resources:
  - url: /local/lovelace-slider-entity-row/slider-entity-row.js
    type: js
  - url: /local/custom-lovelace/alarm_control_panel-card/alarm_control_panel-card.js
    type: module
  - url: /local/mini-media-player-bundle.js?v=0.9.8
    type: module


title: Home Assistant
views:


#################################################################
## Home

  - title: Home
    path: home
    cards:

      - type: entities
        title: Lights
        show_header_toggle: false
        entities:
          - type: custom:slider-entity-row
            entity: light.livingroom_light_level
            toggle: true
          - type: custom:slider-entity-row
            entity: light.kitchen_light_level
            toggle: true
          - type: custom:slider-entity-row
            entity: light.diningroom_light_level
            toggle: true
          - type: custom:slider-entity-row
            entity: light.bedroom_light_level
            toggle: true
          - type: custom:slider-entity-row
            entity: light.bathroom_light_level
            toggle: true
          - type: custom:slider-entity-row
            entity: light.hallway_light_level
            toggle: true
          - type: custom:slider-entity-row
            entity: light.nightstand1
            toggle: true
          - type: custom:slider-entity-row
            entity: light.nightstand2
            toggle: true

      - type: entities
        title: Things
        show_header_toggle: false
        entities:
          - input_select.scene_selector
          - switch.bedroom_outlet_switch_3
          - switch.kitchen_outlet_switch
          - switch.livingroom_outlet_switch_3
          - sensor.dishwasher_status
          - vacuum.roomba
          - climate.dining_room
          - entity: media_player.viziotv
            type: "custom:mini-media-player"
            show_source: small
            hide_controls: true
            hide_mute: true
            volume_stateless: true
            power_color: true
            group: true
          - entity: media_player.nadc338
            type: "custom:mini-media-player"
            show_source: small
            hide_controls: true
            hide_mute: true
            volume_stateless: true
            power_color: true
            group: true

      - type: vertical-stack
        cards:
          - type: entities
            title: Playlist Control
            show_header_toggle: false
            entities:
              - input_select.playlist_content
              - input_select.playlist_source
          - type: horizontal-stack
            cards:
              - type: entity-button
                name: Play
                tap_action:
                  action: call-service
                  service: script.turn_on
                  service_data:
                    entity_id: script.playlist_action
                icon: mdi-blank
                entity: script.playlist_action
              - type: entity-button
                name: Stop
                tap_action:
                  action: call-service
                  service: script.turn_on
                  service_data:
                    entity_id: script.playlist_stop
                icon: mdi-blank
                entity: script.playlist_stop
              - type: entity-button
                name: Vol Down
                tap_action:
                  action: call-service
                  service: script.turn_on
                  service_data:
                    entity_id: script.playlist_voldown
                icon: mdi-blank
                entity: script.playlist_voldown
              - type: entity-button
                name: Vol Up
                tap_action:
                  action: call-service
                  service: script.turn_on
                  service_data:
                    entity_id: script.playlist_volup
                icon: mdi-blank
                entity: script.playlist_volup

      - type: conditional
        conditions:
          - entity: media_player.living_room
            state_not: "off"
          - entity: media_player.living_room
            state_not: "unavailable"
        card:
          type: custom:mini-media-player
          entity: media_player.living_room
          artwork: cover
          short_info: true
          power_color: true
          show_progress: true
          hide_mute: true
          volume_stateless: true

      - type: conditional
        conditions:
          - entity: media_player.kitchen_hub
            state_not: "off"
          - entity: media_player.kitchen_hub
            state_not: "unavailable"
        card:
          type: custom:mini-media-player
          entity: media_player.kitchen_hub
          artwork: cover
          short_info: true
          power_color: true
          show_progress: true
          hide_mute: true
          volume_stateless: true

      - type: conditional
        conditions:
          - entity: media_player.kitchen_stereo
            state_not: "off"
          - entity: media_player.kitchen_stereo
            state_not: "unavailable"
        card:
          type: custom:mini-media-player
          entity: media_player.kitchen_stereo
          artwork: cover
          short_info: true
          power_color: true
          show_progress: true
          hide_mute: true
          volume_stateless: true

      - type: conditional
        conditions:
          - entity: media_player.bedroom_speaker
            state_not: "off"
          - entity: media_player.bedroom_speaker
            state_not: "unavailable"
        card:
          type: custom:mini-media-player
          entity: media_player.bedroom_speaker
          artwork: cover
          short_info: true
          power_color: true
          show_progress: true
          hide_mute: true
          volume_stateless: true

      - type: conditional
        conditions:
          - entity: media_player.basement_group
            state_not: "off"
          - entity: media_player.basement_group
            state_not: "unavailable"
        card:
          type: custom:mini-media-player
          entity: media_player.basement_group
          artwork: cover
          short_info: true
          power_color: true
          show_progress: true
          hide_mute: true
          volume_stateless: true

#      - type: weather-forecast
#        entity: weather.dark_sky

#      - type: picture-entity
#        entity: camera.midwest_radar
#        show_state: false


#################################################################
## Security

  - title: Security
    path: security
    cards:

      - type: custom:alarm_control_panel-card
        entity: alarm_control_panel.main
        show_keypad: true
        title: Alarm Control
        hide_keypad: true
        style: '--alarm-color-disarmed: var(--label-badge-blue);'
        states:
          - arm_home
          - arm_away

      - type: entities
        title: Locks
        show_header_toggle: false
        entities:
          - lock.front_door_handle_locked

      - type: glance
        title: Occupancy Sensors
        entities:
          - binary_sensor.user1_occupancy
          - binary_sensor.user2_occupancy
          - binary_sensor.user3_occupancy
          - binary_sensor.user4_occupancy

      - type: glance
        title: Door Sensors
        entities:
          - binary_sensor.frontdoor_contact
          - binary_sensor.sidedoor_contact
          - binary_sensor.backdoor_contact

      - type: glance
        title: Motion Sensors
        entities:
          - binary_sensor.uplivingroom_motion_sensor
          - binary_sensor.upoffice_motion_sensor
          - binary_sensor.hallway_motion1_sensor
          - binary_sensor.hallway_motion2_sensor
          - binary_sensor.bathroom_motion_sensor

      - type: picture-entity
        entity: camera.frontdoor
        show_state: false
      - type: picture-entity
        entity: camera.backdoor
        show_state: false


#################################################################
## Settings

  - title: Settings
    path: settings
    cards:

      - type: entities
        title: Automation Override
        show_header_toggle: false
        entities:
          - input_boolean.disable_bathroom_lights
          - input_boolean.disable_hallway_lights
          - input_boolean.disable_kitchen_lights
          - input_boolean.disable_bathroom_heater
          - input_boolean.disable_nest
          - input_boolean.disable_roomba_schedule
          - input_boolean.disable_bathroom_heater_schedule
          - input_boolean.disable_lock_automation
          - input_boolean.disable_alarm_system
          - alarm_control_panel.main
          - switch.bedroom_outlet_switch_2
          - switch.livingroom_outlet_switch_2

      - type: entities
        title: Alarm Clock
        show_header_toggle: false
        entities:
          - input_boolean.alarmclock_enabled_wd
          - input_datetime.alarmclock_time_wd
          - type: section
          - input_boolean.alarmclock_enabled_we
          - input_datetime.alarmclock_time_we
          - type: section
          - input_boolean.alarmclock_espresso
          - input_select.alarmclock_content
          - input_boolean.alarmclock_cancel

      - type: entities
        title: Media Override
        show_header_toggle: false
        entities:
          - media_player.viziotv
          - media_player.basement_group
          - media_player.living_room
          - media_player.kitchen_stereo
          - media_player.nadc338
          - media_player.bedroom_speaker
          - media_player.kitchen_hub

      - type: entities
        title: Sensors
        show_header_toggle: false
        entities:
          - sensor.user1_bedroom
          - sensor.user1_office
          - sensor.user1_upstairs
          - type: section
          - sensor.user2_bedroom
          - sensor.user2_office
          - sensor.user2_upstairs
          - type: section
          - sensor.user3_bedroom
          - sensor.user3_office
          - sensor.user3_upstairs
          - type: section
          - sensor.user4_bedroom
          - sensor.user4_office
          - sensor.user4_upstairs
