
##################################################
## Delivery Notification
##################################################

group:
  deliveries:
    name: Deliveries
    entities:
#    - sensor.usps_mail
#    - sensor.usps_packages
    - sensor.ups
    - sensor.fedex
    - sensor.deliveries_today
    - sensor.packages_in_transit
#    - camera.usps_mail

sensor:
  - platform: ups
    name: 'UPS'
    username: REDACTED
    password: 'REDACTED'

  - platform: fedex
    name: 'Fedex'
    username: REDACTED
    password: 'REDACTED'

  - platform: template
    sensors:
      packages_in_transit:
        friendly_name: "Packages in Transit"
        value_template: >
          {% macro in_transit(sensor) %}
            {% if sensor %}
              {{sensor.state|int - delivered(sensor)|int}}
            {% else %}
              0
            {% endif %}
          {% endmacro %}
          {% macro delivered(sensor) %}
            {% if 'delivered' in sensor.attributes %}
              {{sensor.attributes.delivered}}
            {% else %}
               0
            {% endif %}
          {% endmacro %}
          {{in_transit(states.sensor.usps_packages)|int + in_transit(states.sensor.ups)|int + in_transit(states.sensor.fedex)|int}}
      deliveries_today:
        friendly_name: "Today's Deliveries"
        value_template: >
          {% macro delivered(sensor) %}
            {% if 'delivered' in sensor.attributes %}
              {{sensor.attributes.delivered}}
            {% else %}
               0
            {% endif %}
          {% endmacro %}
          {{delivered(states.sensor.usps_packages)|int + delivered(states.sensor.ups)|int + delivered(states.sensor.fedex)|int}}
