
##################################################
## Inputs
input_boolean:

  disable_bathroom_lights:
  disable_hallway_lights:
  disable_kitchen_lights:

#################################################################
## Automations
automation:

  # Bathroom lights on with motion 20min
  - alias: Lights - Bathroom Motion On
    initial_state: True

    trigger:
      platform: state
      entity_id: binary_sensor.bathroom_motion_sensor
      to: 'on'

    condition:
      - condition: state
        entity_id: light.bathroom_light_level
        state: 'off'
      - condition: state
        entity_id: input_boolean.disable_bathroom_lights
        state: 'off'

    action:
      service: homeassistant.turn_on
      entity_id: light.bathroom_light_level
      data_template:
        brightness: >
          {%- if now().strftime('%H')| int >= 23 %}
            40
          {%- elif now().strftime('%H')| int < 7 %}
            40
          {%- elif now().strftime('%H')| int >= 7 %}
            253
          {%- endif %}

  - alias: Lights - Bathroom Motion Off
    initial_state: True

    trigger:
      - platform: state
        entity_id: binary_sensor.bathroom_motion_sensor
        to: 'off'
        from: 'on'
        for:
          minutes: 21

    action:
      service: homeassistant.turn_off
      entity_id: light.bathroom_light_level


  # Hallway lights on from motion or door 15min
  - alias: Lights - Hallway Motion On
    initial_state: True

    trigger:
      - platform: state
        entity_id: binary_sensor.hallway_motion1_sensor, binary_sensor.hallway_motion2_sensor, binary_sensor.backdoor_contact
        to: 'on'

    condition:
      - condition: state
        entity_id: light.hallway_light_level
        state: 'off'
        for:
          minutes: 1
      - condition: state
        entity_id: input_boolean.disable_hallway_lights
        state: 'off'

    action:
      service: homeassistant.turn_on
      entity_id: light.hallway_light_level
      data:
        brightness: 100

  - alias: Lights - Hallway Motion Off
    initial_state: True

    trigger:
      - platform: state
        entity_id: binary_sensor.hallway_motion1_sensor, binary_sensor.hallway_motion2_sensor
        to: 'off'
        for:
          minutes: 11

    condition:
      - condition: state
        entity_id: binary_sensor.hallway_motion1_sensor
        state: 'off'
      - condition: state
        entity_id: binary_sensor.hallway_motion2_sensor
        state: 'off'

    action:
      service: homeassistant.turn_off
      entity_id: light.hallway_light_level

  # Dark arrive home lights
  - alias: Lights - Arrive Kitchen Lights
    initial_state: True

    trigger:
      platform: state
      entity_id: binary_sensor.backdoor_contact
      to: 'on'

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.disable_kitchen_lights
          state: 'off'
        - condition: state
          entity_id: light.kitchen_light_level
          state: 'off'
        - condition: state
          entity_id: light.diningroom_light_level
          state: 'off'
        - condition: or
          conditions:
            - condition: template
              value_template: "{{ (as_timestamp(now())-as_timestamp(states.binary_sensor.user1_occupancy.last_changed)) < 300 }}"
            - condition: template
              value_template: "{{ (as_timestamp(now())-as_timestamp(states.binary_sensor.user2_occupancy.last_changed)) < 300 }}"

    action:
      - service: homeassistant.turn_on
        entity_id: light.kitchen_light_level
        data:
          brightness: 175
      - service: homeassistant.turn_on
        entity_id: light.diningroom_light_level
        data:
          brightness: 100
