
#################################################################
## Automation
automation:

  ##### Media Power Management ######
  # Turn off living_room when Vizio powered off
  - alias: living_room off with vizio

    trigger:
      - platform: state
        entity_id: media_player.viziotv
        to: 'off'

    condition:
      - condition: template
        value_template: "{{ not is_state('media_player.living_room', 'off') }}"

    action:
      - service: homeassistant.turn_off
        entity_id: media_player.living_room

  # Turn off vizio off if chrome cast idle 30 minutes
  - alias: vizio off with chromecast idle

    trigger:
      - platform: state
        entity_id: media_player.living_room
        to: 'off'
        for:
          minutes: 30

    condition:
      - condition: state
        entity_id: media_player.viziotv
        state: 'on'
      - condition: template
        value_template: '{{ states.media_player.viziotv.attributes.source == "HDMI-2" }}'

    action:
      - service: homeassistant.turn_off
        entity_id: media_player.viziotv


  ##### Volume setting ######
  # Set bedroom_speaker volume when turned on
  - alias: bedroom_speaker volume reset

    trigger:
      - platform: state
        entity_id: media_player.bedroom_speaker
        from: 'off'

    condition:
      - condition: state
        entity_id: script.alarmclock_activate
        state: 'off'

    action:
      - service: media_player.volume_set
        data:
          entity_id: media_player.bedroom_speaker
          volume_level: 0.5

  # Set bedroom_speaker volume when turned on basement_group
  - alias: bedroom_speaker volume reset basement_group

    trigger:
      - platform: state
        entity_id: media_player.basement_group
        from: 'off'

    condition:
      - condition: state
        entity_id: script.alarmclock_activate
        state: 'off'

    action:
      - service: media_player.volume_set
        data:
          entity_id: media_player.bedroom_speaker
          volume_level: 0.5

  # Set nadc338 volume when turned on
  - alias: nadc338 volume reset

    trigger:
      - platform: state
        entity_id: media_player.nadc338
        from: 'off'

    condition:
      - condition: state
        entity_id: script.alarmclock_activate
        state: 'off'

    action:
      - service: media_player.volume_set
        data:
          entity_id: media_player.nadc338
          volume_level: 0.65
      

  # Set nadc338 volume when input changed
  - alias: nadc338 volume reset input changed

    trigger:
      - platform: template
        value_template: '{{ states.media_player.nadc338.attributes.source == "Wireless" }}'
      - platform: template
        value_template: '{{ states.media_player.nadc338.attributes.source == "Stream" }}'

    condition:
      - condition: state
        entity_id: script.alarmclock_activate
        state: 'off'

    action:
      - service: media_player.volume_set
        data:
          entity_id: media_player.nadc338
          volume_level: 0.65


  # Reset living_room volume everyday
  - alias: living_room volume reset

    trigger:
      - platform: time
        at: '05:00:00'

    action:
      - service: media_player.volume_set
        data:
          entity_id: media_player.living_room
          volume_level: 1.0

  # Reset kitchen_home volume everyday
  - alias: kitchen_home volume reset

    trigger:
      - platform: time
        at: '12:00:00'

    action:
      - service: media_player.volume_set
        data:
          entity_id: media_player.kitchen_home
          volume_level: 0.5
