
##################################################
## Sensors

sensor:
  - platform: rest
    name: Home Assistant Release
    resource: https://api.github.com/repos/home-assistant/home-assistant/releases/latest
    username: !secret github_username
    password: !secret github_access_token
    authentication: basic
    value_template: '{{ value_json.tag_name }}'
    headers:
      Accept: application/vnd.github.v3+json
      Content-Type: application/json
      User-Agent: Home Assistant REST sensor

  - platform: version


#################################################################
## Automations
automation:

  # Notify when HA update is available
  - alias: Home Assistant Release Check
    initial_state: True

    trigger:
    - platform: state
      entity_id: sensor.home_assistant_release
    - platform: homeassistant
      event: start

    condition:
      condition: template
      value_template:  "{{ states('sensor.home_assistant_release') != states('sensor.current_version') }}"

    action:
      - service: notify.html5
        data:
          title: 'New Home Assistant Release - {{ states("sensor.home_assistant_release") }}'
          message: 'Home Assistant update is now available. - {{now().strftime("%l:%M %P")}}'
          data:
            requireInteraction: true

  # Set HA theme on startup
  - alias: 'Set theme at startup'
    initial_state: True
    trigger:
      - platform: homeassistant
        event: start

    action:
      service: frontend.set_theme
      data:
        name: dark
